openapi: 3.0.2
info:
  title: Doml to Domlx converter API
  description: It converts doml to domlx format and domlx to doml format
  version: 1.0.0
  license:
    name: Copyright © Piacere 2023
servers:
  - url: "/d2x/api/v1"
    description: v1 api
  - url: https://ci.piacere.digital.tecnalia.dev/d2x/api/v1
    description: Integration server
  - url: http://d2x.192.168.56.1.nip.io/d2x/api/v1
    description: local vagrant server
  - url: http://d2x.localhost:8080/d2x/api/v1
    description: development locally
paths:
  /doml2domlx:
    post:
      summary: Doml to Domlx.
      description: Convert Doml to Domlx.
      requestBody:
        description: Doml file.
        required: true
        content:
          text/plain:
            schema:
              type: string
      responses:
        '201':    # status code
          description: A JSON array of user names
          content:
            application/xml:
              schema:
                type: string
  /domlx2doml:
    post:
      summary: Domlx to Doml.
      description: Convert Domlx to Doml.
      requestBody:
        description: Domlx file.
        required: true
        content:
          application/xml:
            schema:
              type: string
      responses:
        '201':    # status code
          description: A JSON array of user names
          content:
            text/plain:
              schema:
                type: string
  /domlecore:
    get:
      summary: Doml ecore.
      description: Get Doml ecore.
      responses:
        '200':    # status code
          description: the ecore in xmi format
          content:
            application/xml:
              schema:
                type: string