openapi: 3.0.0
info:
  description: It converts doml to domlx format and domlx to doml format
  title: Doml to Domlx converter API
  version: 0.1.9
servers:
- description: Integration server
  url: https://ci.piacere.digital.tecnalia.dev
- description: local vagrant server
  url: http://d2x.192.168.56.1.nip.io/v1
- description: development locally
  url: http://d2x.localhost:8080/v1
paths:
  /doml2domlx:
    post:
      description: Convert Doml to Domlx.
      requestBody:
        content:
          text/plain:
            schema:
              type: string
        description: Doml file.
        required: true
      responses:
        "201":
          content:
            application/xml:
              schema:
                type: string
          description: A JSON array of user names
      summary: Doml to Domlx.
      x-content-type: text/plain
      x-accepts: application/xml
  /domlx2doml:
    post:
      description: Convert Domlx to Doml.
      requestBody:
        content:
          application/xml:
            schema:
              type: string
        description: Domlx file.
        required: true
      responses:
        "201":
          content:
            text/plain:
              schema:
                type: string
          description: A JSON array of user names
      summary: Domlx to Doml.
      x-content-type: application/xml
      x-accepts: text/plain
components:
  schemas: {}
