services:
  d2x:
    build:
      context: ${D2X_BASE_PATH}.
      dockerfile: Dockerfile
      cache_from:
        - ${IMAGE_D2X_CACHE:?err}
      args:
        BUILDKIT_INLINE_CACHE: 1 # For multistage docker

      # https://github.com/jfrog/artifactory-user-plugins/tree/master/cleanup/cleanDockerImages
